# build on top of out base image
FROM pypelinerhackathon/python_wgs:v0.1.1

ADD . /app

# Install any needed packages specified in requirements.txt
RUN rm -rf /opt/conda/lib/python2.7/site-packages/pypeliner* /opt/conda/lib/python2.7/site-packages/single_cell_pipeline* /opt/conda/lib/python2.7/site-packages/biowrappers*
RUN cd /app && python setup.py install
RUN pip install git+https://github.com/shahcompbio/pypeliner.git@v0.5.18
RUN pip install git+https://github.com/shahcompbio/biowrappers.git@v0.2.8
# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME alignment

# Run app.py when the container launches
CMD ["alignment"]
